Repository zerospam/freshbooks-sdk, pull requests merged in 2018-09, with the labels that each got.

#33 Add late payment fees
  src/Business/Enums/Client/Fee/LatePaymentFeeType.php
  src/Business/LatePaymentFee.php
  src/Request/Data/Client/ClientData.php
  src/Request/Data/Client/LatePayment/FeeData.php
  src/Response/Clients/ClientResponse.php
  tests/src/Requests/Client/ClientTest.php
Labels: enhancement

#36 Add late payment, reminders and presentations
  src/Request/Call/Invoice/Presentations/PresentationsReadRequest.php
  src/Request/Data/Client/ClientData.php
  src/Request/Data/Client/LatePayment/CommonWriteLatePaymentReminders.php
  src/Request/Data/Invoice/InvoiceCreateData.php
  src/Response/Invoice/Presentation/PresentationResponse.php
  tests/src/Requests/Invoice/Presentations/PresentationsTest.php
Labels: enhancement

#37 Add invoice index filtering
  composer.lock
  src/Argument/SearchArrayArgument.php
  src/Business/Enums/Estimate/EstimateStatusEnum.php
  src/Business/Enums/Estimate/UIEstimateStatusEnum.php
  src/Business/Enums/Invoice/InvoiceStatusEnum.php
  src/Response/Estimate/EstimateResponse.php
  src/Response/Invoice/InvoiceResponse.php
  tests/src/Requests/Estimate/EstimateTest.php
  tests/src/Requests/Invoice/InvoiceTest.php
Labels: ready for review

#41 feat(Estimate): Added payment method enumeration
  src/Business/Enums/Payment/PaymentMethodEnum.php
  src/Business/Report/PaymentsCollected/Payment.php
  tests/src/Requests/Report/ReportTest.php
Labels: ready for review

#43 refactor(Currency): Refactored currency properties to use Currency en…
  src/Business/Amount.php
  src/Business/Enums/Currency/CurrencyEnum.php
  src/Business/Report/InvoiceDetails/Invoice.php
  src/Business/Report/PaymentsCollected/Payment.php
  src/Request/Data/AmountData.php
  src/Request/Data/Client/ClientData.php
  src/Request/Data/Common/CommonWritableFields.php
  src/Request/Data/InvoiceProfile/InvoiceProfileData.php
  src/Response/Clients/ClientResponse.php
  src/Response/Estimate/EstimateResponse.php
  src/Response/Invoice/InvoiceResponse.php
  src/Response/InvoiceProfile/InvoiceProfileResponse.php
  src/Response/Report/ReportAccountsAgingResponse.php
  src/Response/Report/ReportExpenseDetailsResponse.php
  src/Response/Report/ReportInvoiceDetailsResponse.php
  src/Response/Report/ReportPaymentsCollectedResponse.php
  src/Response/Report/ReportProfitLossResponse.php
  src/Response/Report/ReportTaxSummaryResponse.php
  tests/src/Requests/Client/ClientTest.php
  tests/src/Requests/Estimate/EstimateTest.php
  tests/src/Requests/Invoice/InvoiceTest.php
  tests/src/Requests/Invoice/Presentations/PresentationsTest.php
  tests/src/Requests/InvoiceProfile/InvoiceProfileTest.php
  tests/src/Requests/Report/ReportTest.php
Labels: enhancement, ready for review
